import "server-only";

import {
  EMBEDDING_BATCH_DELAY_MS,
  EMBEDDING_BATCH_SIZE,
  EMBEDDING_TIMEOUT_MS,
  GEMINI_EMBEDDING_DIMENSIONS,
  RAG_FRESHNESS_DAYS,
  RAG_MATCH_COUNT,
  RAG_MAX_CHUNKS_PER_DESTINATION,
  RAG_MAX_CONTEXT_CHARS,
  RAG_MIN_CHUNKS,
  RAG_SIMILARITY_THRESHOLD,
  WIKIMEDIA_TIMEOUT_MS,
  WIKIMEDIA_USER_AGENT,
} from "@/lib/rag/constants-shared";

export {
  EMBEDDING_BATCH_DELAY_MS,
  EMBEDDING_BATCH_SIZE,
  EMBEDDING_TIMEOUT_MS,
  GEMINI_EMBEDDING_DIMENSIONS,
  RAG_FRESHNESS_DAYS,
  RAG_MATCH_COUNT,
  RAG_MAX_CHUNKS_PER_DESTINATION,
  RAG_MAX_CONTEXT_CHARS,
  RAG_MIN_CHUNKS,
  RAG_SIMILARITY_THRESHOLD,
  WIKIMEDIA_TIMEOUT_MS,
  WIKIMEDIA_USER_AGENT,
};

/** Gemini text embedding model used for travel RAG. */
export const GEMINI_EMBEDDING_MODEL =
  process.env.GEMINI_EMBEDDING_MODEL?.trim() || "gemini-embedding-001";
